"""Reporter for benchmark results - markdown, csv, charts."""
import csv
import os
from datetime import datetime
from typing import List, Dict, Any


def generate_report(results: List[Dict], output_path: str, system_info: str = "Enhancement MultiAgent 0.2.0 - Ollama + FastMCP + OpenCV"):
    psnr_vals = [r["metrics"]["psnr"] for r in results if "error" not in r["metrics"]]
    ssim_vals = [r["metrics"]["ssim"] for r in results if "error" not in r["metrics"]]
    mse_vals = [r["metrics"]["mse"] for r in results if "error" not in r["metrics"]]
    avg_psnr = round(sum(psnr_vals)/len(psnr_vals),2) if psnr_vals else 0
    avg_ssim = round(sum(ssim_vals)/len(ssim_vals),4) if ssim_vals else 0
    avg_mse = round(sum(mse_vals)/len(mse_vals),2) if mse_vals else 0
    best_psnr = max(psnr_vals) if psnr_vals else 0
    worst_psnr = min(psnr_vals) if psnr_vals else 0
    best_ssim = max(ssim_vals) if ssim_vals else 0
    worst_ssim = min(ssim_vals) if ssim_vals else 0

    # Quality gate stats
    passed = sum(1 for r in results if r.get("quality",{}).get("final_pass", True))
    report = f"""# \U0001f5bc\ufe0f Augmentation Benchmark Report

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Total Images:** {len(results)}
**Quality Gate Pass Rate:** {passed}/{len(results)} ({passed/max(len(results),1)*100:.1f}%)
**System:** {system_info}

---

## \U0001f4ca Summary Statistics

| Metric | Average | Best | Worst |
|--------|---------|------|-------|
| **PSNR (dB)** | {avg_psnr} | {best_psnr} | {worst_psnr} |
| **SSIM** | {avg_ssim} | {best_ssim} | {worst_ssim} |
| **MSE** | {avg_mse} | — | — |
| **Diversity (1-hist_corr)** | {round(sum(r['metrics'].get('diversity',0) for r in results if 'metrics' in r and 'diversity' in r['metrics'])/max(len(psnr_vals),1),3) if psnr_vals else 0} | — | — |

### Interpretation
- **PSNR > 30 dB**: Excellent preservation (for restoration) / Low diversity (for augmentation may want lower)
- **SSIM > 0.90**: Structural similarity preserved
- **Diversity > 0.3**: Good augmentation variability
- **Quality Gate** aggregates classical + perceptual + Vision LLM.

---

## \U0001f4cb Per-Image Results

| # | Image | PSNR ↑ | SSIM ↑ | MSE ↓ | Diversity | Quality | Time (s) |
|---|-------|--------|--------|-------|-----------|---------|----------|
"""
    for i, r in enumerate(results,1):
        if "error" in r["metrics"]:
            report += f"| {i} | `{r['image']}` | — | — | — | — | ❌ | {r['time']:.1f} |\n"
        else:
            q = "✅" if r.get("quality",{}).get("final_pass", True) else "⚠️"
            report += f"| {i} | `{r['image']}` | {r['metrics']['psnr']} | {r['metrics']['ssim']} | {r['metrics']['mse']} | {r['metrics'].get('diversity','-')} | {q} | {r['time']:.1f} |\n"

    # Best/worst
    valid = [r for r in results if "error" not in r["metrics"]]
    if valid:
        best = max(valid, key=lambda x: x["metrics"]["psnr"])
        worst = min(valid, key=lambda x: x["metrics"]["psnr"])
        report += f"""
---

## \U0001f50d Detailed Findings

### \U0001f3c6 Best Preservation
- **Image:** `{best['image']}` PSNR {best['metrics']['psnr']} SSIM {best['metrics']['ssim']}

### \u26a0\ufe0f Lowest Preservation (highest diversity)
- **Image:** `{worst['image']}` PSNR {worst['metrics']['psnr']} SSIM {worst['metrics']['ssim']}
- **Reason:** Intentional heavy augmentation (e.g., brightness shift) naturally lowers PSNR - not necessarily bad; Vision LLM validates semantic keep.
"""
    report += f"""
---

## \U0001f6e0\ufe0f System Configuration
| Component | Details |
|-----------|---------|
| LLM Engine | Ollama (llama3.2, llava vision) |
| Tool Protocol | MCP (FastMCP) |
| Image Processing | OpenCV 4.x |
| Agents | 3 specialized (Geometric, Photometric, Generative) + Orchestrator |
| Quality Gates | Classical / Perceptual / Vision LLM (extensible) |
| Planner | Model-aware Augmentation Planner with Feedback Loop |
| Integrations | PyTorch / TensorFlow / Hugging Face hooks |

---
*Generated by Enhancement MultiAgent Benchmark Suite v0.2.0*
"""
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report)
    return report


def generate_csv(results: List[Dict], output_path: str):
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["image","psnr","ssim","mse","mae","diversity","quality_pass","time_seconds"])
        for r in results:
            if "error" in r["metrics"]:
                writer.writerow([r["image"], "", "", "", "", "", "failed", f"{r['time']:.2f}"])
            else:
                m = r["metrics"]
                qpass = r.get("quality", {}).get("final_pass", "")
                writer.writerow([r["image"], m.get("psnr",""), m.get("ssim",""), m.get("mse",""), m.get("mae",""), m.get("diversity",""), qpass, f"{r['time']:.2f}"])


def generate_visualization(results: List[Dict], output_path: str):
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        valid = [r for r in results if "error" not in r["metrics"]]
        if not valid:
            return
        names = [r["image"][:15] for r in valid]
        psnr_vals = [r["metrics"]["psnr"] for r in valid]
        ssim_vals = [r["metrics"]["ssim"] for r in valid]
        diversity = [r["metrics"].get("diversity",0) for r in valid]
        fig, axes = plt.subplots(3,1, figsize=(12,10))
        # PSNR
        colors = ["green" if p>30 else "orange" if p>25 else "red" for p in psnr_vals]
        axes[0].bar(range(len(names)), psnr_vals, color=colors, edgecolor="black", linewidth=0.5)
        axes[0].set_xticks(range(len(names))); axes[0].set_xticklabels(names, rotation=45, ha="right", fontsize=8)
        axes[0].set_ylabel("PSNR (dB)"); axes[0].set_title("PSNR per Image (preservation)"); axes[0].grid(axis="y", alpha=0.3)
        # SSIM
        colors2 = ["green" if s>0.9 else "orange" if s>0.8 else "red" for s in ssim_vals]
        axes[1].bar(range(len(names)), ssim_vals, color=colors2, edgecolor="black", linewidth=0.5)
        axes[1].set_xticks(range(len(names))); axes[1].set_xticklabels(names, rotation=45, ha="right", fontsize=8)
        axes[1].set_ylabel("SSIM"); axes[1].set_title("SSIM per Image"); axes[1].grid(axis="y", alpha=0.3)
        # Diversity
        axes[2].bar(range(len(names)), diversity, color="steelblue", edgecolor="black", linewidth=0.5)
        axes[2].set_xticks(range(len(names))); axes[2].set_xticklabels(names, rotation=45, ha="right", fontsize=8)
        axes[2].set_ylabel("Diversity"); axes[2].set_title("Augmentation Diversity (1 - hist corr)"); axes[2].grid(axis="y", alpha=0.3)
        plt.tight_layout()
        plt.savefig(output_path, dpi=150, bbox_inches="tight")
        plt.close()
        print(f"   📊 Visualization saved: {output_path}")
    except Exception as e:
        print(f"   ⚠️ Visualization failed: {e}")
